#!/bin/sh
PREREQ=""
prereqs()
{
   echo "$PREREQ"
}

case $1 in
prereqs)
   prereqs
   exit 0
   ;;
esac

mount_count=$(tune2fs -l $root | grep "Mount count" | cut -d: -f 2 | tr -d " ")

echo "Mount count: $mount_count" >> /run/auto-fsck.log

if [ "$mount_count" -gt "30" ]; then
    fsck -a $root >> /run/auto-fsck.log 2>&1
    tune2fs -C 0 $root >> /run/auto-fsck.log
fi

exit 0
